# Generated by Django 3.1.2 on 2020-11-03 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_logitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
