# Generated by Django 3.1.1 on 2020-11-16 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_auto_20201103_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='alcohol',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In g per 100g of product', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='alcohol'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calcium',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In g per 100g of product', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='calcium'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='iron',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In g per 100g of product', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='iron'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_a',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In g per 100g of product', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Vitamin A'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamin_c',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In g per 100g of product', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Vitamin C'),
        ),
    ]
