# Generated by Django 3.1.1 on 2020-12-01 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20201103_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('description', models.CharField(blank=True, help_text='Wellness atribute filling for determinate user', max_length=80, verbose_name='Description')),
                ('language', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.language', verbose_name='Language')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='WellnessEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Date')),
                ('wellness_date', models.DateField()),
                ('wellnes_energy', models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')], verbose_name='Energía')),
                ('wellnes_sleep', models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')])),
                ('wellnes_motivation', models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')])),
                ('wellnes_stress', models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')])),
                ('wellnes_hungry', models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')])),
                ('wellnes_steps', models.IntegerField(default=500)),
                ('wellnes_bath', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('wellnes_fasting', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('language', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.language', verbose_name='Language')),
            ],
            options={
                'ordering': ['wellness_date'],
            },
        ),
    ]
